### ISSUE TITLE
the answer is not accurate

### ISSUE THREAD

**Issue by zhangbiao2009** [paulbellamy/ratecounter#15]
this small program sometimes outputs 30, sometimes outputs 27, I expect it should always output 30:

```Go
package main

import (
	"fmt"
	"time"

	"github.com/paulbellamy/ratecounter"
)

func main() {
	counter := ratecounter.NewRateCounter(1 * time.Second)
	for {
		for i := 0; i < 10; i++ {
			counter.Incr(1)
			counter.Incr(1)
			counter.Incr(1)
			time.Sleep(99 * time.Millisecond)
		}
		fmt.Println(counter.Rate())
	}
}
```

**Comment by paulbellamy** [comment]
Sometimes doing:
```Go
counter.Incr(1)
counter.Incr(1)
counter.Incr(1)
```
takes longer than 1 ms, making the total time taken > 100 ms. On those instances only 27 ticks have happened per second.

By using a ticker for the loop we are independent of how long `Incr` takes to call. Try this version:
```Go
package main

import (
	"fmt"
	"time"

	"github.com/paulbellamy/ratecounter"
)

func main() {
	counter := ratecounter.NewRateCounter(1 * time.Second)
	ticker := time.NewTicker(100 * time.Millisecond)
	for {
		for i := 0; i < 10; i++ {
			<-ticker.C
			counter.Incr(1)
			counter.Incr(1)
			counter.Incr(1)
		}

		fmt.Println(counter.Rate())
	}
	ticker.Stop()
}
```

Without a hard real-time OS to make timing guarantees all rate-counting and timing should be considered best-effort. Especially considering garbage-collecting.
