### ISSUE TITLE
TestAvgRateCounterAdvanced fails

### ISSUE THREAD

**Issue by aviau** [paulbellamy/ratecounter#16]
I am getting the following output:
```
--- FAIL: TestAvgRateCounterAdvanced (1.50s)
	avgratecounter_test.go:39: Expected rate  1.5  to equal  3
	avgratecounter_test.go:42: Expected hits  2  to equal  1
```

Any idea what may cause this?

**Comment by paulbellamy** [comment]
Hmm.. Could be a race condition in the tests. Do you see it consistently or only sometimes?

**Comment by aviau** [comment]
Yep, and it happens on machines with high load (the Debian CI).

**Comment by paulbellamy** [comment]
Using a clock library which allows mocking out timers would probably help.
