### ISSUE TITLE
Use a single timer, instead of making a new one for every mark, so we don't thrash the GC

### ISSUE THREAD

**Issue by paulbellamy** [paulbellamy/ratecounter#2]

**Comment by dzlab** [comment]
Why not use something like [time.AfterFunc](https://golang.org/pkg/time/#AfterFunc) that could be triggered each second. I think it's more efficient than using many goroutines (i.e [scheduleDecrement(amount int64)](https://github.com/paulbellamy/ratecounter/blob/master/ratecounter.go#L25)) that would just decrement by one (e.g. requests by second) after sleeping for the duration of an interval.

**Comment by suedadam** [comment]
Did this ever get looked into?

**Comment by paulbellamy** [comment]
Not yet, but I'd be happy to accept a PR if it's bugging you.

**Comment by sheerun** [comment]
As for the cost: of this From what I read each goroutine weights around 4kb, and you create one each increment per duration. So if you set rate per hour and there's 100000 requests per hour it will need 400mb of memory

**Comment by sheerun** [comment]
I've sent improved implementation in PR #2
