### ISSUE TITLE
Documentation outdated for counter Incr

### ISSUE THREAD

**Issue by narapon** [paulbellamy/ratecounter#21]
The current docs show the outdated way to increment the counter using counter.Mark() :
- [https://pkg.go.dev/github.com/paulbellamy/ratecounter?tab=doc](https://pkg.go.dev/github.com/paulbellamy/ratecounter?tab=doc)

- [https://pkg.go.dev/github.com/paulbellamy/ratecounter?tab=doc](https://godoc.org/github.com/paulbellamy/ratecounter)

according to the updated README it is now counter.Incr(int)

**Comment by paulbellamy** [comment]
Good catch! Thanks.
