### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [paulbellamy/ratecounter#5]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for ratecounter and versioning would help Debian keep up with development.

**Comment by paulbellamy** [comment]
Do you have an example of this?

**Comment by aviau** [comment]
To understand versioning in general and pick out good version numbers, I suggest you read the SemVer spec: http://semver.org/

Here is an example of a golang library that is versioned: https://github.com/go-xorm/xorm

As you can see, there are git tags that correspond to version numbers (click on the release tab).

**Comment by paulbellamy** [comment]
Created release v0.1.0 (https://github.com/paulbellamy/ratecounter/releases/tag/v0.1.0).

If you need anything else, do let me know. :)

**Comment by aviau** [comment]
Thank you for this!

Make sure you keep tagging from time to time as you integrate new features and fix bugs.
